// Code generated by github.com/atombender/go-jsonschema.
// Adjusted to use the json package from github.com/cisco-open/sprt/frontend-svc/internal/json

package schemas

import (
	"fmt"
	"reflect"

	"github.com/cisco-open/sprt/frontend-svc/internal/json"
)

type GenerateJson struct {
	// Coa corresponds to the JSON schema field "coa".
	Coa *GenerateJsonCoa `json:"coa,omitempty" yaml:"coa,omitempty" mapstructure:"coa,omitempty"`

	// General corresponds to the JSON schema field "general".
	General GenerateJsonGeneral `json:"general" yaml:"general" mapstructure:"general"`

	// Guest corresponds to the JSON schema field "guest".
	Guest *GenerateJsonGuest `json:"guest,omitempty" yaml:"guest,omitempty" mapstructure:"guest,omitempty"`

	// IpAddresses corresponds to the JSON schema field "ipAddresses".
	IpAddresses interface{} `json:"ipAddresses" yaml:"ipAddresses" mapstructure:"ipAddresses"`

	// MacAddresses corresponds to the JSON schema field "macAddresses".
	MacAddresses interface{} `json:"macAddresses" yaml:"macAddresses" mapstructure:"macAddresses"`

	// Radius corresponds to the JSON schema field "radius".
	Radius GenerateJsonRadius `json:"radius" yaml:"radius" mapstructure:"radius"`

	// Scheduler corresponds to the JSON schema field "scheduler".
	Scheduler interface{} `json:"scheduler,omitempty" yaml:"scheduler,omitempty" mapstructure:"scheduler,omitempty"`
}

type GenerateJsonCoa struct {
	// OnBounceHostPort corresponds to the JSON schema field "onBounceHostPort".
	OnBounceHostPort interface{} `json:"onBounceHostPort,omitempty" yaml:"onBounceHostPort,omitempty" mapstructure:"onBounceHostPort,omitempty"`

	// OnDefault corresponds to the JSON schema field "onDefault".
	OnDefault interface{} `json:"onDefault,omitempty" yaml:"onDefault,omitempty" mapstructure:"onDefault,omitempty"`

	// OnDisableHostPort corresponds to the JSON schema field "onDisableHostPort".
	OnDisableHostPort interface{} `json:"onDisableHostPort,omitempty" yaml:"onDisableHostPort,omitempty" mapstructure:"onDisableHostPort,omitempty"`

	// OnReauthenticateDefault corresponds to the JSON schema field
	// "onReauthenticateDefault".
	OnReauthenticateDefault interface{} `json:"onReauthenticateDefault,omitempty" yaml:"onReauthenticateDefault,omitempty" mapstructure:"onReauthenticateDefault,omitempty"`

	// OnReauthenticateLast corresponds to the JSON schema field
	// "onReauthenticateLast".
	OnReauthenticateLast interface{} `json:"onReauthenticateLast,omitempty" yaml:"onReauthenticateLast,omitempty" mapstructure:"onReauthenticateLast,omitempty"`

	// OnReauthenticateRerun corresponds to the JSON schema field
	// "onReauthenticateRerun".
	OnReauthenticateRerun interface{} `json:"onReauthenticateRerun,omitempty" yaml:"onReauthenticateRerun,omitempty" mapstructure:"onReauthenticateRerun,omitempty"`
}

type GenerateJsonGeneral struct {
	// Job corresponds to the JSON schema field "job".
	Job GenerateJsonGeneralJob `json:"job" yaml:"job" mapstructure:"job"`

	// Nas corresponds to the JSON schema field "nas".
	Nas GenerateJsonGeneralNas `json:"nas" yaml:"nas" mapstructure:"nas"`

	// Server corresponds to the JSON schema field "server".
	Server GenerateJsonGeneralServer `json:"server" yaml:"server" mapstructure:"server"`
}

type GenerateJsonGeneralJob struct {
	// BulkName corresponds to the JSON schema field "bulkName".
	BulkName string `json:"bulkName" yaml:"bulkName" mapstructure:"bulkName"`

	// Latency corresponds to the JSON schema field "latency".
	Latency interface{} `json:"latency" yaml:"latency" mapstructure:"latency"`

	// LatencyAcctStart corresponds to the JSON schema field "latencyAcctStart".
	LatencyAcctStart interface{} `json:"latencyAcctStart" yaml:"latencyAcctStart" mapstructure:"latencyAcctStart"`

	// MultiThread corresponds to the JSON schema field "multiThread".
	MultiThread bool `json:"multiThread" yaml:"multiThread" mapstructure:"multiThread"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// SaveSessions corresponds to the JSON schema field "saveSessions".
	SaveSessions bool `json:"saveSessions" yaml:"saveSessions" mapstructure:"saveSessions"`

	// SessionsAmount corresponds to the JSON schema field "sessionsAmount".
	SessionsAmount float64 `json:"sessionsAmount" yaml:"sessionsAmount" mapstructure:"sessionsAmount"`

	// WithAcctStart corresponds to the JSON schema field "withAcctStart".
	WithAcctStart bool `json:"withAcctStart" yaml:"withAcctStart" mapstructure:"withAcctStart"`

	// WithDACL corresponds to the JSON schema field "withDACL".
	WithDACL bool `json:"withDACL" yaml:"withDACL" mapstructure:"withDACL"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonGeneralJob) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["bulkName"]; raw != nil && !ok {
		return fmt.Errorf("field bulkName in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["latency"]; raw != nil && !ok {
		return fmt.Errorf("field latency in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["latencyAcctStart"]; raw != nil && !ok {
		return fmt.Errorf("field latencyAcctStart in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["multiThread"]; raw != nil && !ok {
		return fmt.Errorf("field multiThread in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["saveSessions"]; raw != nil && !ok {
		return fmt.Errorf("field saveSessions in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["sessionsAmount"]; raw != nil && !ok {
		return fmt.Errorf("field sessionsAmount in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["withAcctStart"]; raw != nil && !ok {
		return fmt.Errorf("field withAcctStart in GenerateJsonGeneralJob: required")
	}
	if _, ok := raw["withDACL"]; raw != nil && !ok {
		return fmt.Errorf("field withDACL in GenerateJsonGeneralJob: required")
	}
	type Plain GenerateJsonGeneralJob
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if 1 > plain.SessionsAmount {
		return fmt.Errorf("field %s: must be >= %v", "sessionsAmount", 1)
	}
	*j = GenerateJsonGeneralJob(plain)
	return nil
}

type GenerateJsonGeneralNas struct {
	// ConnectionType corresponds to the JSON schema field "connectionType".
	ConnectionType string `json:"connectionType" yaml:"connectionType" mapstructure:"connectionType"`

	// Mtu corresponds to the JSON schema field "mtu".
	Mtu float64 `json:"mtu" yaml:"mtu" mapstructure:"mtu"`

	// NasIp corresponds to the JSON schema field "nasIp".
	NasIp string `json:"nasIp" yaml:"nasIp" mapstructure:"nasIp"`

	// Retransmits corresponds to the JSON schema field "retransmits".
	Retransmits float64 `json:"retransmits" yaml:"retransmits" mapstructure:"retransmits"`

	// SessionIdTemplate corresponds to the JSON schema field "sessionIdTemplate".
	SessionIdTemplate string `json:"sessionIdTemplate" yaml:"sessionIdTemplate" mapstructure:"sessionIdTemplate"`

	// Timeout corresponds to the JSON schema field "timeout".
	Timeout float64 `json:"timeout" yaml:"timeout" mapstructure:"timeout"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonGeneralNas) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["connectionType"]; raw != nil && !ok {
		return fmt.Errorf("field connectionType in GenerateJsonGeneralNas: required")
	}
	if _, ok := raw["mtu"]; raw != nil && !ok {
		return fmt.Errorf("field mtu in GenerateJsonGeneralNas: required")
	}
	if _, ok := raw["nasIp"]; raw != nil && !ok {
		return fmt.Errorf("field nasIp in GenerateJsonGeneralNas: required")
	}
	if _, ok := raw["retransmits"]; raw != nil && !ok {
		return fmt.Errorf("field retransmits in GenerateJsonGeneralNas: required")
	}
	if _, ok := raw["sessionIdTemplate"]; raw != nil && !ok {
		return fmt.Errorf("field sessionIdTemplate in GenerateJsonGeneralNas: required")
	}
	if _, ok := raw["timeout"]; raw != nil && !ok {
		return fmt.Errorf("field timeout in GenerateJsonGeneralNas: required")
	}
	type Plain GenerateJsonGeneralNas
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.ConnectionType) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "connectionType", 1)
	}
	if 1 > plain.Mtu {
		return fmt.Errorf("field %s: must be >= %v", "mtu", 1)
	}
	if len(plain.NasIp) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "nasIp", 1)
	}
	if 0 > plain.Retransmits {
		return fmt.Errorf("field %s: must be >= %v", "retransmits", 0)
	}
	if len(plain.SessionIdTemplate) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "sessionIdTemplate", 1)
	}
	if 0 > plain.Timeout {
		return fmt.Errorf("field %s: must be >= %v", "timeout", 0)
	}
	*j = GenerateJsonGeneralNas(plain)
	return nil
}

type GenerateJsonGeneralServer struct {
	// AcctPort corresponds to the JSON schema field "acctPort".
	AcctPort float64 `json:"acctPort" yaml:"acctPort" mapstructure:"acctPort"`

	// Address corresponds to the JSON schema field "address".
	Address string `json:"address" yaml:"address" mapstructure:"address"`

	// AuthPort corresponds to the JSON schema field "authPort".
	AuthPort float64 `json:"authPort" yaml:"authPort" mapstructure:"authPort"`

	// LoadedId corresponds to the JSON schema field "loadedId".
	LoadedId *string `json:"loadedId,omitempty" yaml:"loadedId,omitempty" mapstructure:"loadedId,omitempty"`

	// Save corresponds to the JSON schema field "save".
	Save bool `json:"save" yaml:"save" mapstructure:"save"`

	// Secret corresponds to the JSON schema field "secret".
	Secret string `json:"secret" yaml:"secret" mapstructure:"secret"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonGeneralServer) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["acctPort"]; raw != nil && !ok {
		return fmt.Errorf("field acctPort in GenerateJsonGeneralServer: required")
	}
	if _, ok := raw["address"]; raw != nil && !ok {
		return fmt.Errorf("field address in GenerateJsonGeneralServer: required")
	}
	if _, ok := raw["authPort"]; raw != nil && !ok {
		return fmt.Errorf("field authPort in GenerateJsonGeneralServer: required")
	}
	if _, ok := raw["save"]; raw != nil && !ok {
		return fmt.Errorf("field save in GenerateJsonGeneralServer: required")
	}
	if _, ok := raw["secret"]; raw != nil && !ok {
		return fmt.Errorf("field secret in GenerateJsonGeneralServer: required")
	}
	type Plain GenerateJsonGeneralServer
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if 65535 < plain.AcctPort {
		return fmt.Errorf("field %s: must be <= %v", "acctPort", 65535)
	}
	if 0 >= plain.AcctPort {
		return fmt.Errorf("field %s: must be > %v", "acctPort", 0)
	}
	if len(plain.Address) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "address", 1)
	}
	if 65535 < plain.AuthPort {
		return fmt.Errorf("field %s: must be <= %v", "authPort", 65535)
	}
	if 0 >= plain.AuthPort {
		return fmt.Errorf("field %s: must be > %v", "authPort", 0)
	}
	*j = GenerateJsonGeneralServer(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonGeneral) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["job"]; raw != nil && !ok {
		return fmt.Errorf("field job in GenerateJsonGeneral: required")
	}
	if _, ok := raw["nas"]; raw != nil && !ok {
		return fmt.Errorf("field nas in GenerateJsonGeneral: required")
	}
	if _, ok := raw["server"]; raw != nil && !ok {
		return fmt.Errorf("field server in GenerateJsonGeneral: required")
	}
	type Plain GenerateJsonGeneral
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = GenerateJsonGeneral(plain)
	return nil
}

type GenerateJsonGuest struct {
	// GuestFlow corresponds to the JSON schema field "guestFlow".
	GuestFlow interface{} `json:"guestFlow,omitempty" yaml:"guestFlow,omitempty" mapstructure:"guestFlow,omitempty"`

	// UserAgents corresponds to the JSON schema field "userAgents".
	UserAgents *GenerateJsonGuestUserAgents `json:"userAgents,omitempty" yaml:"userAgents,omitempty" mapstructure:"userAgents,omitempty"`
}

type GenerateJsonGuestUserAgents struct {
	// AllowRepeats corresponds to the JSON schema field "allowRepeats".
	AllowRepeats *bool `json:"allowRepeats,omitempty" yaml:"allowRepeats,omitempty" mapstructure:"allowRepeats,omitempty"`

	// Dictionaries corresponds to the JSON schema field "dictionaries".
	Dictionaries []string `json:"dictionaries,omitempty" yaml:"dictionaries,omitempty" mapstructure:"dictionaries,omitempty"`

	// Select corresponds to the JSON schema field "select".
	Select *GenerateJsonGuestUserAgentsSelect `json:"select,omitempty" yaml:"select,omitempty" mapstructure:"select,omitempty"`
}

type GenerateJsonGuestUserAgentsSelect string

const GenerateJsonGuestUserAgentsSelectRandom GenerateJsonGuestUserAgentsSelect = "random"
const GenerateJsonGuestUserAgentsSelectSequential GenerateJsonGuestUserAgentsSelect = "sequential"

var enumValues_GenerateJsonGuestUserAgentsSelect = []interface{}{
	"sequential",
	"random",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonGuestUserAgentsSelect) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GenerateJsonGuestUserAgentsSelect {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GenerateJsonGuestUserAgentsSelect, v)
	}
	*j = GenerateJsonGuestUserAgentsSelect(v)
	return nil
}

type GenerateJsonRadius struct {
	// Attributes corresponds to the JSON schema field "attributes".
	Attributes GenerateJsonRadiusAttributes `json:"attributes" yaml:"attributes" mapstructure:"attributes"`

	// Dictionaries corresponds to the JSON schema field "dictionaries".
	Dictionaries []string `json:"dictionaries" yaml:"dictionaries" mapstructure:"dictionaries"`
}

type GenerateJsonRadiusAttributes struct {
	// AccessRequest corresponds to the JSON schema field "accessRequest".
	AccessRequest []interface{} `json:"accessRequest" yaml:"accessRequest" mapstructure:"accessRequest"`

	// AccountingStart corresponds to the JSON schema field "accountingStart".
	AccountingStart []interface{} `json:"accountingStart" yaml:"accountingStart" mapstructure:"accountingStart"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonRadiusAttributes) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["accessRequest"]; raw != nil && !ok {
		return fmt.Errorf("field accessRequest in GenerateJsonRadiusAttributes: required")
	}
	if _, ok := raw["accountingStart"]; raw != nil && !ok {
		return fmt.Errorf("field accountingStart in GenerateJsonRadiusAttributes: required")
	}
	type Plain GenerateJsonRadiusAttributes
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = GenerateJsonRadiusAttributes(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJsonRadius) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["attributes"]; raw != nil && !ok {
		return fmt.Errorf("field attributes in GenerateJsonRadius: required")
	}
	if _, ok := raw["dictionaries"]; raw != nil && !ok {
		return fmt.Errorf("field dictionaries in GenerateJsonRadius: required")
	}
	type Plain GenerateJsonRadius
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = GenerateJsonRadius(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerateJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["general"]; raw != nil && !ok {
		return fmt.Errorf("field general in GenerateJson: required")
	}
	if _, ok := raw["ipAddresses"]; raw != nil && !ok {
		return fmt.Errorf("field ipAddresses in GenerateJson: required")
	}
	if _, ok := raw["macAddresses"]; raw != nil && !ok {
		return fmt.Errorf("field macAddresses in GenerateJson: required")
	}
	if _, ok := raw["radius"]; raw != nil && !ok {
		return fmt.Errorf("field radius in GenerateJson: required")
	}
	type Plain GenerateJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = GenerateJson(plain)
	return nil
}
