// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/strmangle"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("models: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type CertType string

// Enum values for CertType
const (
	CertTypeIdentity CertType = "identity"
	CertTypeTrusted  CertType = "trusted"
	CertTypeSigner   CertType = "signer"
)

func AllCertType() []CertType {
	return []CertType{
		CertTypeIdentity,
		CertTypeTrusted,
		CertTypeSigner,
	}
}

func (e CertType) IsValid() error {
	switch e {
	case CertTypeIdentity, CertTypeTrusted, CertTypeSigner:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e CertType) String() string {
	return string(e)
}

func (e CertType) Ordinal() int {
	switch e {
	case CertTypeIdentity:
		return 0
	case CertTypeTrusted:
		return 1
	case CertTypeSigner:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}

type Protos string

// Enum values for Protos
const (
	ProtosRadius Protos = "radius"
	ProtosTacacs Protos = "tacacs"
)

func AllProtos() []Protos {
	return []Protos{
		ProtosRadius,
		ProtosTacacs,
	}
}

func (e Protos) IsValid() error {
	switch e {
	case ProtosRadius, ProtosTacacs:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e Protos) String() string {
	return string(e)
}

func (e Protos) Ordinal() int {
	switch e {
	case ProtosRadius:
		return 0
	case ProtosTacacs:
		return 1

	default:
		panic(errors.New("enum is not valid"))
	}
}
