// Code generated by plugin-builder; DO NOT EDIT.
package plugins_gen

import (
	_ "github.com/cisco-open/sprt/go-generator/generator/plugins/mab"
	_ "github.com/cisco-open/sprt/go-generator/generator/plugins/pap"
	_ "github.com/cisco-open/sprt/go-generator/generator/plugins/eaptls"
	_ "github.com/cisco-open/sprt/go-generator/generator/plugins/peap"
)
